version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kompetisiku
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  app:
    image: data_forms
    ports:
      - 8080:5005