version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kompetisiku
    restart: always
  web:
    build: ./backend
    environment:
      MYSQL_DATABASE: kompetisiku
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure